[package]
name = "discord-matrix-bridge"
version = "0.1.0"
edition = "2021"
authors = ["Charlotte 🦝 Delenk <lotte@chir.rs>"]
rust-version = "1.60.0"
description = "Application Service that bridges Discord to Matrix"
readme = "README.md"
repository = "https://github.com/DarkKirb/discord-bridge"
license = "Apache-2.0"
keywords = ["matrix", "discord", "bridge"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
color-eyre = "0.6.1"
dotenv = "0.15.0"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"

[dependencies.ruma]
version = "0.6.1"
features = ["client-reqwest-rustls-webpki-roots"]
