name: Automatic suggestions
on: pull_request

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: rustfmt made the following change
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = nixcache:8KKuGz95Pk4UJ5W/Ni+pN+v+LDTkMMFV4yrGmAYgkDg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://f000.backblazeb2.com/file/cache-chir-rs/ https://cache.nixos.org/
      - run: nix fmt flake.nix
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: rustfmt made the following change
